# Generated by Django 5.0.14 on 2026-02-26 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number (digits only, optional leading '+').", regex='^\\+?\\d{7,20}$')]),
        ),
    ]
