# Generated by Django 5.0.14 on 2026-02-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
        ('accounts', '0003_create_site'),
    ]

    operations = [
    ]
