# Generated by Django 5.0.14 on 2026-03-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_manage_products', 'Can manage products'), ('can_manage_orders', 'Can manage all orders')]},
        ),
    ]
