# Generated by Django 5.0.14 on 2026-04-21 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('orders', '0012_alter_orderitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='adminnote',
            name='customer',
        ),
        migrations.AddField(
            model_name='notification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adminnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminnote',
            name='order',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order'),
        ),
    ]
