# Generated by Django 5.0.14 on 2026-04-21 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_adminnote_options_alter_notification_options_and_more'),
        ('orders', '0012_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_notes', to='orders.order'),
        ),
    ]
