# Generated by Django 5.0.14 on 2026-04-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_adminnote_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
    ]
