# Generated by Django 5.0.14 on 2026-04-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('order_update', 'Actualización de pedido'), ('stock_change', 'Cambio de stock'), ('product_create', 'Creación de producto'), ('product_update', 'Actualización de producto'), ('product_delete', 'Eliminación de producto')], max_length=50),
        ),
    ]
