# Generated by Django 5.0.14 on 2026-03-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_orders', 'Can view all orders'), ('can_change_order_status', 'Can change order status'), ('can_change_payment_status', 'Can change payment status')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
