# Generated by Django 5.0.14 on 2026-03-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
