# Generated by Django 5.0.14 on 2026-04-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_address_order_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_orders', 'Puede ver todos los pedidos'), ('can_change_order_status', 'Puede cambiar el estado del pedido'), ('can_change_payment_status', 'Puede cambiar el estado del pago')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Ítem del pedido', 'verbose_name_plural': 'Ítems del pedido'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'No pagado'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='unpaid', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('paid', 'Pagado'), ('fulfilled', 'Entregado')], default='pending', max_length=20),
        ),
    ]
