# Generated by Django 5.0.14 on 2026-04-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('packed', 'Empaquetado'), ('shipped', 'Enviado'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado'), ('returned', 'Devuelto'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
