# Generated by Django 5.0.14 on 2026-04-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'No pagado'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('packed', 'Empacado'), ('shipped', 'Enviado'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado'), ('returned', 'Devuelto'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
