# Generated by Django 5.0.14 on 2026-04-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
