# Generated by Django 5.0.14 on 2026-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('manual', 'Ajuste manual'), ('order', 'Pedido'), ('restock', 'Reabastecimiento'), ('system', 'Sistema')], default='manual', max_length=50),
        ),
    ]
